CREATE INDEX "SO_FACTS_BY_PERIOD_IDX_COMPANY" on "ERPI"."SO_FACTS_BY_PERIOD"("FISCAL_VARIANT_K", "COMPANY_K");
CREATE INDEX "SO_FACTS_BY_PERIOD_IDX_LVL1" on "ERPI"."SO_FACTS_BY_PERIOD"("FISCAL_VARIANT_K", "CUSTOMER_K");
CREATE INDEX "SO_FACTS_BY_PERIOD_IDX_ORDER" on "ERPI"."SO_FACTS_BY_PERIOD"("FISCAL_VARIANT_K", "ORDER_K");
